### ISSUE TITLE
Make the size more optimal for tablets

### ISSUE THREAD

**Issue by jroweboy** [FiveGuys-CS256/html-prototype#2]
Our current font size and our current left hand side recipe tabs seems to be on the small side. I don't have a tablet so I can't tell for sure, but my gut tells me it might be a little bit hard to read on a smaller device screen. We should consider making them bigger and adding more space to the left hand side ingredients list.

**Comment by kbpontius** [comment]
I agree!

**Comment by liukaichi** [comment]
I also agree.
